const {DataTypes} = require("sequelize");
const sequelize = require("../sequelize");

const Products = sequelize.define('products',{
    productId:{
        type:DataTypes.UUID,
        defaultValue:DataTypes.UUIDV4,
        primaryKey:true,
        unique:true,
    },
    productName:{
        type:DataTypes.STRING,
        allowNull:true
    },
    productSlug:{
        type:DataTypes.STRING,
        allowNull:false,
        unique:true
    },
    productshortDesc:{
        type:DataTypes.TEXT,
        allowNull:true
    },
    productAddInfo:{
        type:DataTypes.ARRAY(DataTypes.TEXT),
        allowNull:true
    },
    productShippingInfo:{
       type:DataTypes.TEXT,
       allowNull:true
    },
    relatedProducts:{
        type:DataTypes.ARRAY(DataTypes.JSONB),
        allowNull:true
    },
    productPrice:{
        type:DataTypes.INTEGER,
        allowNull:true
    },
    productsalePrice:{
        type:DataTypes.INTEGER,
        allowNull:true
    },
    productReview:{
        type:DataTypes.INTEGER,
        allowNull:true,
        defaultValue:0,
    },
    productUntill:{
        type:DataTypes.DATEONLY,
        allowNull:true
    },
    productStock:{
        type:DataTypes.INTEGER,
        allowNull:true,
        defaultValue:0,
    },
    productTop:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    productNew:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    producEmbroidered:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    productAuthor:{
        type:DataTypes.UUID,
        allowNull:false,
    },
    productSold:{
        type:DataTypes.BOOLEAN,
        allowNull:true
    },
    productCategory:{
        type:DataTypes.ARRAY(DataTypes.JSONB),
        allowNull:true
    },
    productOccasion:{
        type:DataTypes.ARRAY(DataTypes.JSONB),
        allowNull:true
    },
    productMaterial:{
        type:DataTypes.ARRAY(DataTypes.JSONB),
        allowNull:true
    },
    productBrands:{
        type:DataTypes.ARRAY(DataTypes.JSONB),
        allowNull:true
    },
    productAmountEarned:{
        type:DataTypes.INTEGER,
        allowNull:true,
        defaultValue:0
    },
    productComments:{
        type:DataTypes.JSONB(DataTypes.TEXT),
        allowNull:true
    }
    //relatedproduct
});

module.exports = Products;